### ISSUE TITLE
helm init flags being parsed incorrectly

### ISSUE THREAD

**Issue by puetzp** [puppetlabs/puppetlabs-helm#73]
When I try to TLS-secure my helm installation, I run into the following error:
```
Error: 'helm init --service-account 'tiller' --tiller-namespace 'kube-system' --tiller-tls-cert '/etc/kubernetes/pki/tiller.crt' --tiller-tls-key '/etc/kubernetes/pki/tiller.key' --tls_ca_cert '/etc/kubernetes/pki/tiller_ca.crt' --upgrade' returned 1 instead of one of [0]
Error: /Stage[main]/Helm::Config/Helm::Helm_init[helm-kube-system-master]/Exec[helm kube-system init]/returns: change from 'notrun' to ['0'] failed: 'helm init --service-account 'tiller' --tiller-namespace 'kube-system' --tiller-tls-cert '/etc/kubernetes/pki/tiller.crt' --tiller-tls-key '/etc/kubernetes/pki/tiller.key' --tls_ca_cert '/etc/kubernetes/pki/tiller_ca.crt' --upgrade' returned 1 instead of one of [0]
```
There seems to be a typo in this ruby function:

https://github.com/puppetlabs/puppetlabs-helm/blob/3739c0ae6db188f21ddafce94c5de64e8f8db653/lib/puppet/parser/functions/helm_init_flags.rb#L31

The flag should be named `--tls-ca-cert`.
Same is true for [dry-run](https://github.com/puppetlabs/puppetlabs-helm/blob/master/lib/puppet/parser/functions/helm_init_flags.rb#L14)

Fortunately just a very minor issue!

**Comment by sheenaajay** [comment]
@puetzp Thanks for raising the issue. Please find the fix.

**Comment by sheenaajay** [comment]
https://github.com/puppetlabs/puppetlabs-helm/pull/85
